### ISSUE TITLE
Error occurs randomly

### ISSUE THREAD

**Issue by Antidotas** [ArubikU/IssuesAndTicket#2]
[22:57:17 INFO]: [MythicMobs] Mythic has finished reloading!
[22:57:31 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[22:57:31 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[22:57:41 INFO]: [ItemsAdder] [Pack] Resource pack successfully compressed. Uploading...
[22:57:41 INFO]: [ItemsAdder] [Pack] Uploading resourcepack...
[22:58:01 INFO]: [ItemsAdder] [Pack] Finished uploading resourcepack: http://resourcepack.host/dl/AAe7ihrrPei26pEWYf1Dqn6fGohVUNmi/pack.zip
[22:58:11 INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (auto-external-host), LastEdit: 2022-07-01_22-58. Url: http://resourcepack.host/dl/AAe7ihrrPei26pEWYf1Dqn6fGohVUNmi/pack.zip
[22:58:11 INFO]: [ItemsAdder] Applying pack to every player...
[22:58:11 INFO]: [ItemsAdder] Applied pack to 1 players
[23:01:12 INFO]: Antidotas issued server command: /time day
[23:02:35 INFO]: [AsyncWorldEdit] Undo cleanup started...
[23:02:35 INFO]: [AsyncWorldEdit] ...undo cleanup done.
[23:02:45 INFO]: [CustomCrafting] Saving Cauldrons
[23:02:46 INFO]: Antidotas issued server command: /iazip
[23:02:46 INFO]: [ItemsAdder] [Pack] Extracting utility resource_pack assets from .jar
[23:02:46 INFO]: [ItemsAdder] [Pack] DONE extracting utility resource_pack assets from .jar
[23:02:49 INFO]: [ItemsAdder] Loaded 764 items
[23:02:49 INFO]: [ItemsAdder] Used 4/188 REAL block IDs
[23:02:49 INFO]: [ItemsAdder] Used 35/750 REAL_NOTE block IDs
[23:02:49 INFO]: [ItemsAdder] Used 8/63 REAL_TRANSPARENT block IDs
[23:02:49 INFO]: [ItemsAdder] Used 114/127 REAL_WIRE block IDs
[23:02:49 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[23:02:49 INFO]: [ItemsAdder] Used 931/6608 font_images
[23:02:49 INFO]: [ItemsAdder] [Init] Loaded 5 categories
[23:02:49 INFO]: [ItemsAdder] [Init] Loaded 764 items and stuff in 2778ms
[23:02:49 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[23:02:49 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[23:02:49 INFO]: [Mythic] Reloading plugin...
[23:02:49 INFO]: [MythicMobs] Mythic beginning reload procedure...
[23:02:49 INFO]: [MythicMobs] Loading Packs...
[23:02:49 INFO]: [MythicMobs] Loading Items...
[23:02:49 INFO]: [MythicMobs] Loading Skills...
[23:02:49 INFO]: [MythicMobs] Loading Drop Tables...
[23:02:49 INFO]: [MythicMobs] Loading Random Spawns...
[23:02:49 INFO]: [MythicMobs] Loading Spawn Blocks...
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 30 mobs.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 3 vanilla mob overrides.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 10 skills.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 2 random spawns.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 3 mythic items.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 2 drop tables.
[23:02:49 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[23:02:49 INFO]: [Mythic] Mythic has finished reloading!
[23:02:49 INFO]: [MythicMobs] Mythic has finished reloading!
[23:03:03 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[23:03:03 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[23:03:13 INFO]: [ItemsAdder] [Pack] Resource pack successfully compressed. Uploading...
[23:03:13 INFO]: [ItemsAdder] [Pack] Uploading resourcepack...
[23:03:33 INFO]: [ItemsAdder] [Pack] Finished uploading resourcepack: http://resourcepack.host/dl/Mm3xgLpLuNkqhCLWkPXSfWyacHb6jE6J/pack.zip
[23:03:44 INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (auto-external-host), LastEdit: 2022-07-01_23-03. Url: http://resourcepack.host/dl/Mm3xgLpLuNkqhCLWkPXSfWyacHb6jE6J/pack.zip
[23:03:44 INFO]: [ItemsAdder] Applying pack to every player...
[23:03:44 INFO]: [ItemsAdder] Applied pack to 1 players
[23:05:15 FATAL]: Thread Craft Scheduler Thread - 92 - IACroper failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[23:05:15 WARN]: [IACroper] Plugin IACroper v2.1.0 generated an exception while executing task 97844
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
>

**Comment by ArubikU** [comment]
Disable furniture mode in config
